export enum NavigationIconType {
  Home = 'Home',
  BotViewer = 'Bot Viewer',
  DataSource = 'Data Source',
  Account = 'Account',
  Calendar = 'Calendar',
  Meet = 'Meet',
  Activity = 'activity',
  Publish = 'publish',
  Saved = 'Saved',
  Settings = 'Settings',
  Contact = 'Contact',
  Profile = 'Profile',
  Compose = 'Compose',
  Inbox = 'Inbox',
  Send = 'Send',
  Draft = 'Draft',
  Configure = 'Configure',
  EmbedSettings = 'EmbedSettings',
  Favourite = 'Favourite',
  Brand = 'brand',
  Poster= 'poster',
}
